/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/kkIxRcoR7fX
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Arimo } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

arimo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"

export function avatar() {
  return (
    <div className="flex flex-col items-center justify-center min-h-[100dvh] bg-background px-4 py-12 sm:px-6 lg:px-8">
      <div className="max-w-md w-full space-y-8">
        <div className="flex flex-col items-center space-y-4">
          <Avatar className="w-24 h-24 border-2 border-primary">
            <AvatarImage src="/placeholder-user.jpg" />
            <AvatarFallback>JD</AvatarFallback>
          </Avatar>
          <div className="text-center space-y-1">
            <h1 className="text-3xl font-bold">John Doe</h1>
            <p className="text-muted-foreground">Software Engineer</p>
          </div>
        </div>
        <div className="grid grid-cols-2 gap-4">
          <div className="bg-muted/20 p-4 rounded-md">
            <h2 className="text-lg font-semibold">About</h2>
            <p className="text-muted-foreground">
              I am a passionate software engineer with a strong background in full-stack web development. I love
              building scalable and user-friendly applications that solve real-world problems.
            </p>
          </div>
          <div className="bg-muted/20 p-4 rounded-md">
            <h2 className="text-lg font-semibold">Skills &amp; Interests</h2>
            <div className="grid grid-cols-2 gap-2 mt-2">
              <div className="bg-muted/20 px-3 py-1 rounded-md text-sm font-medium">React</div>
              <div className="bg-muted/20 px-3 py-1 rounded-md text-sm font-medium">Node.js</div>
              <div className="bg-muted/20 px-3 py-1 rounded-md text-sm font-medium">TypeScript</div>
              <div className="bg-muted/20 px-3 py-1 rounded-md text-sm font-medium">Databases</div>
              <div className="bg-muted/20 px-3 py-1 rounded-md text-sm font-medium">Algorithms</div>
              <div className="bg-muted/20 px-3 py-1 rounded-md text-sm font-medium">UI/UX Design</div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
