/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/7Gx0DMn25Co
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"

export function notsure() {
  return (
    <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3 max-w-6xl mx-auto p-4">
      <div className="bg-background rounded-lg overflow-hidden shadow-lg col-span-1 sm:col-span-1 lg:col-span-1">
        <div className="flex items-center gap-4 p-4">
          <Avatar className="w-16 h-16">
            <AvatarImage src="/placeholder-user.jpg" />
            <AvatarFallback>JD</AvatarFallback>
          </Avatar>
          <div className="grid gap-1">
            <h3 className="text-lg font-semibold">John Doe</h3>
            <p className="text-sm text-muted-foreground">Software Engineer</p>
          </div>
        </div>
        <p className="p-4 text-sm text-muted-foreground">
          John is a talented software engineer with a passion for building innovative solutions. He has extensive
          experience in full-stack development and is always eager to learn new technologies.
        </p>
      </div>
      <div className="bg-background rounded-lg overflow-hidden shadow-lg col-span-1 sm:col-span-2 lg:col-span-1">
        <div className="flex items-center gap-4 p-4">
          <Avatar className="w-16 h-16">
            <AvatarImage src="/placeholder-user.jpg" />
            <AvatarFallback>JS</AvatarFallback>
          </Avatar>
          <div className="grid gap-1">
            <h3 className="text-lg font-semibold">Jane Smith</h3>
            <p className="text-sm text-muted-foreground">Product Manager</p>
          </div>
        </div>
        <p className="p-4 text-sm text-muted-foreground">
          Jane is a seasoned product manager with a keen eye for user experience. She has a track record of successfully
          launching products that delight customers and drive business growth.
        </p>
      </div>
      <div className="bg-background rounded-lg overflow-hidden shadow-lg col-span-1 sm:col-span-1 lg:col-span-2">
        <div className="flex items-center gap-4 p-4">
          <Avatar className="w-16 h-16">
            <AvatarImage src="/placeholder-user.jpg" />
            <AvatarFallback>MJ</AvatarFallback>
          </Avatar>
          <div className="grid gap-1">
            <h3 className="text-lg font-semibold">Michael Johnson</h3>
            <p className="text-sm text-muted-foreground">UI/UX Designer</p>
          </div>
        </div>
        <p className="p-4 text-sm text-muted-foreground">
          Michael is a talented UI/UX designer with a keen eye for aesthetics and a deep understanding of human-centered
          design principles. He has a passion for creating intuitive and visually stunning interfaces that delight
          users.
        </p>
      </div>
      <div className="bg-background rounded-lg overflow-hidden shadow-lg col-span-1 sm:col-span-1 lg:col-span-1">
        <div className="flex items-center gap-4 p-4">
          <Avatar className="w-16 h-16">
            <AvatarImage src="/placeholder-user.jpg" />
            <AvatarFallback>ED</AvatarFallback>
          </Avatar>
          <div className="grid gap-1">
            <h3 className="text-lg font-semibold">Emily Davis</h3>
            <p className="text-sm text-muted-foreground">Data Analyst</p>
          </div>
        </div>
        <p className="p-4 text-sm text-muted-foreground">
          Emily is a skilled data analyst with a passion for uncovering insights that drive business decisions. She has
          a strong background in statistical analysis and data visualization, and is adept at translating complex data
          into actionable recommendations.
        </p>
      </div>
      <div className="bg-background rounded-lg overflow-hidden shadow-lg col-span-1 sm:col-span-2 lg:col-span-1">
        <div className="flex items-center gap-4 p-4">
          <Avatar className="w-16 h-16">
            <AvatarImage src="/placeholder-user.jpg" />
            <AvatarFallback>DL</AvatarFallback>
          </Avatar>
          <div className="grid gap-1">
            <h3 className="text-lg font-semibold">David Lee</h3>
            <p className="text-sm text-muted-foreground">DevOps Engineer</p>
          </div>
        </div>
        <p className="p-4 text-sm text-muted-foreground">
          David is a skilled DevOps engineer with a passion for automating and streamlining infrastructure and
          deployment processes. He has a deep understanding of cloud technologies and is adept at implementing scalable
          and reliable infrastructure solutions.
        </p>
      </div>
    </div>
  )
}
